### PR TITLE
Properly deal with refdefs inside blockquotes

### LINKED ISSUE #398: panic in reference links with newlines
The following markdown:

```
[`cargo
package`]

[`cargo package`]: https://example.com
```

Causes a panic in 0.6.  Bisected regression to #386.

<details><summary>Backtrace</summary>
<pre>
thread 'main' panicked at 'attempt to subtract with overflow', src/parse.rs:1684:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: pulldown_cmark::parse::scan_link_label::{{closure}}
             at src/parse.rs:1684
  12: pulldown_cmark::linklabel::scan_link_label_rest
             at src/linklabel.rs:79
  13: pulldown_cmark::parse::scan_link_label
             at src/parse.rs:1693
  14: pulldown_cmark::parse::Parser::handle_inline_pass1
             at src/parse.rs:2141
  15: pulldown_cmark::parse::Parser::handle_inline
             at src/parse.rs:1958
  16: <pulldown_cmark::parse::Parser as core::iter::traits::iterator::Iterator>::next
             at src/parse.rs:2787
  17: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:2608
  18: pulldown_cmark::html::HtmlWriter<I,W>::run
             at ./src/html.rs:146
  19: pulldown_cmark::html::write_html
             at ./src/html.rs:514
  20: pulldown_cmark::main
             at src/main.rs:100
  21: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: std::panicking::try
             at src/libstd/panicking.rs:275
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  29: pulldown_cmark::main
</pre>
</details>

### PR DESCRIPTION
**Pull request by marcusklaas**
There was an edge case with code spans within refdef labels. We relied on jumping to the next node whenever we encountered a newline inside a block (like a list or a blockquote), but code spans are always one node. This PR should cover this as well.

Closes #398.

### CODE REVIEW

**Comment by marcusklaas** [comment]
The latest commit is a start for tackling #399. It's a bit tricky since we currently assume that inline HTML can always be represented by a slice of the source document, but this fails for markdown like this:
```md
> this is inline <abbr
> title="hypertext markup language">html</abbr> yo
```
Fortunately, this can be fixed without breaking backward compatibility, but I'm struggling to come up with a solution with manageable complexity. To be continued..

**Comment by ehuss** [comment]
Thanks!  From my perspective, 398 is more important than 399.  I'd love to start using 0.6 with all its improvements, and I think 398 is the only blocker.  399 has an easy workaround (don't wrap tags in blockquotes).

I can imagine the complexities of dealing with blockquotes. I wrote a word-wrapping plugin that handles many different formats including markdown blockquotes and code comments blocks, so I'm familiar with the frustrations of trying to parse this kind of stuff.

File: src/linklabel.rs [hunk 1]
```diff
@@ -34,22 +34,17 @@ pub type LinkLabel<'a> = UniCase<CowStr<'a>>;
...
-    start: usize,
-    linebreak_handler: F,
-) -> Option<(usize, CowStr<'_>)>
-where
-    // Takes a _global_ index into the document string, returns how many bytes to skip
-    F: Fn(usize) -> Option<usize>,
-{
+pub(crate) fn scan_link_label_rest<'t>(
+    text: &'t str,
+    linebreak_handler: &dyn Fn(&[u8]) -> Option<usize>,
```
Comment (raphlinus) [inline src/linklabel.rs]: Any special reason for going `dyn` here? I expect performance to degrade slightly, but of course I don't know that without measuring.

Also, I think it would be useful to have a one-line comment (in the `///` section) explaining the signature, as it's not immediately obvious when reading the code.

Comment (marcusklaas) [reply src/linklabel.rs]: It's to reduce code bloat (a few KiB by my measurement) for fairly cold routines (linebreaks inside HTML). Figured it was worth the trade-off here.

I'll add a comment explaining the linebreak handler. It is there to facilitate reusing the code for inline HTML. Inline HTML can contain linebreaks and may need access to some context which isn't part of the function arguments.

As described above, this solution isn't particularly elegant and I plan to separate the routines for inline/ block HTML at some point.

**Comment by ehuss** [comment]
Thanks for the fix!  I was wondering if you could make a new release?  I'd like to get https://github.com/rust-lang/mdBook/pull/1021 merged.

**Comment by marcusklaas** [comment]
Working on a new release right now!

**Comment by marcusklaas** [comment]
It's released finally: https://crates.io/crates/pulldown-cmark/0.6.1
